development:
  adapter: postgresql
  encoding: unicode
  database: horndo_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: horndo_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: horndo_production
  pool: 5
  host: localhost

