default: &default
adapter: postgresql
encoding: unicode
pool: 5

development:
<<: *default
database: horndo_production

test:
<<: *default
database: horndo

production: &default
adapter: postgresql
database: horndo_production
encoding: utf8
min_messages: warning
pool: 5
timeout: 5000